clone_folder: c:\gopath\src\github.com\deis\workflow-cli

environment:
  GOPATH: C:\gopath

install:
  - ps: (new-object net.webclient).DownloadFile('https://github.com/Masterminds/glide/releases/download/0.10.2/glide-0.10.2-windows-amd64.zip', 'C:\glide.zip')
  - ps: 7z e C:\glide.zip -oC:\glide
  - ps: $env:Path += ";C:\glide\"
  - ps: .\make bootstrap

build_script:
  - ps: .\make build

test_script:
  - ps: .\make test

artifacts:
  - path: deis.exe
    name: deis.exe
